### PR TITLE
[PG-1313] Remove Online status

### PR DESCRIPTION
**Pull request by avi-bh**
### JIRA Ticket
https://bighealth.atlassian.net/browse/PG-1313

### Problem
As a user using the community forum, I do not want my online status to be advertised so that my privacy is preserved.

### Solution
* Comment out FE component that gives users the ability to modify presence.
* Add validation for the BE endpoint to not allow users to make `is_hiding_presence` False.
* Add a DB migration to make the default value of `is_hiding_presence` True.

#### Unit tests + Integration Tests
* Until we can easily run tests, this is tough to confirm. Given blast radius of changes, I will address whatever test fixes are needed as part of my next ticket, https://bighealth.atlassian.net/browse/PG-1435.

#### Manual Tests
* Confirmed manually in Dev.

### CODE REVIEW

**Review by jjosephbh — DISMISSED** [review]

**Review by wsbastian — APPROVED** [review]
LGTM

**Review by wsbastian — COMMENTED** [review]
How are these changes being packaged/built? Would we expect to see them in misago.js or vendor.js?

**Review by wsbastian — CHANGES_REQUESTED** [review]
let's do a gulp build to update minified misago.js

**Review by crfelizbh — DISMISSED** [review]
lgtm

**Review by wsbastian — DISMISSED** [review]
LGTM

**Review by wsbastian — APPROVED** [review]

**Review by eliot-mestre — APPROVED** [review]

**Pull request merged**
